theme: jekyll-theme-cayman
remote_theme: tuur29/pages-themes-cayman
title: Ziqian Xia
description: Ziqian.research@gmail.com
show_downloads: true
color:
  header: "#FFFFFF"
  gradient_left: "#30E8BF"
  gradient_right: "#FF8235"
buttons:
      zip_url: https://github.com/Ziqian-xia/Ziqian-xia.github.io/blob/gh-pages/CV-Ziqian.pdf
      zip_title: CV
      zip_hide: false
      tar_url: http://example.com/
      tar_title: Latest Talk
      tar_hide: true
      github_hide: true # hides "View on Github"
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
  - index.md
