theme: jekyll-theme-cayman
remote_theme: tuur29/pages-themes-cayman
title: Ziqian Xia
description: Environmental Psychology & Economics
show_downloads: true
color:
  header: "#FFFFFF"
  gradient_left: "#8360c3"
  gradient_right: "#2ebf91"
buttons:
      zip_url: http://example.com/
      zip_title: CV
      zip_hide: false
      tar_url: http://example.com/
      tar_title: Latest Talk
      tar_hide: true
      github_hide: true # hides "View on Github"
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
  - index.md
