theme: jekyll-theme-cayman
title: Ziqian Xia
description: Environmental Psychology & Economics
show_downloads: true
remote_theme: tuur29/pages-themes-cayman
color:
  header: "#FFFFFF"
  gradient_left: "#005AA7"
  gradient_right: "#FFFDE4"
buttons:
      zip_url: http://example.com/
      zip_title: Title
      zip_hide: false
      tar_url: http://example.com/
      tar_title: Title
      tar_hide: false
      github_hide: true # hides "View on Github"
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
  - index.md
